language: java
jdk:
  - oraclejdk8
#  - oraclejdk7
#  - openjdk7
before_install:
  - pip install codecov
install: true
sudo: require
script: 
  - mvn clean verify test
after_success:
  - codecov
  
  